name: RunOnBamToBigWig
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::samtools=1.19.0
  - bioconda::bedtools=2.28.0
  # No version specified
  - bioconda::ucsc-bedgraphtobigwig
